FROM postgres:latest

ENV POSTGRES_USER root
ENV POSTGRES_PASSWORD 123
ENV POSTGRES_DB gerenciador-pedidos

EXPOSE 5433

#docker run -d -p 5433:5432 --name postegresformsdronepedidos postegresformsdronepedidos