FROM postgres:latest

ENV POSTGRES_USER root
ENV POSTGRES_PASSWORD 123
ENV POSTGRES_DB monitoramento

EXPOSE 5434

#docker run -d -p 5434:5432 --name postegresformsmonitoramento postegresformsmonitoramento