FROM postgres:latest

ENV POSTGRES_USER root
ENV POSTGRES_PASSWORD 123
ENV POSTGRES_DB gerenciador-cadastros

EXPOSE 5432

#docker run -d -p 5432:5432 --name postegresformsdronecadastro postgresformsdronecadastro